
// This file was auto-generated by ML.NET Model Builder. 

using ImageClassificationModel_ConsoleApp;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\M_IT_01\source\repos\ImageClassification\ImageClassification.win\IntelImageClassificationDataSet\seg_train\seg_train\buildings\0.jpg");
ImageClassificationModel.ModelInput sampleData = new ImageClassificationModel.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = ImageClassificationModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
